"""forecast channel shares

Revision ID: 133b08597c36
Revises: 4415d8a04fe9
Create Date: 2026-10-04 01:18:42.449275

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "133b08597c36"
down_revision: str | None = "4415d8a04fe9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forecast_channel_shares",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("channel_id", sa.UUID(), nullable=False),
        sa.Column("share", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("units_90d", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["forecast_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "run_id", "product_id", "channel_id", name="uq_forecast_channel_shares"
        ),
    )
    op.create_index(
        op.f("ix_forecast_channel_shares_org_id"),
        "forecast_channel_shares",
        ["org_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_forecast_channel_shares_org_id"), table_name="forecast_channel_shares")
    op.drop_table("forecast_channel_shares")
    # ### end Alembic commands ###
