"""initial schema

Revision ID: a2002a8113fb
Revises:
Create Date: 2026-10-03 17:28:19.192811

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "a2002a8113fb"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "locations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_locations_org_id"), "locations", ["org_id"], unique=False)
    op.create_table(
        "product_categories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "name", name="uq_product_categories_org_name"),
    )
    op.create_index(
        op.f("ix_product_categories_org_id"), "product_categories", ["org_id"], unique=False
    )
    op.create_table(
        "regions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "code", name="uq_regions_org_code"),
    )
    op.create_index(op.f("ix_regions_org_id"), "regions", ["org_id"], unique=False)
    op.create_table(
        "suppliers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("lead_time_days", sa.Integer(), nullable=False),
        sa.Column("moq", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_suppliers_org_id"), "suppliers", ["org_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("external_auth_id", sa.String(length=200), nullable=True),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "email", name="uq_users_org_email"),
    )
    op.create_index(op.f("ix_users_org_id"), "users", ["org_id"], unique=False)
    op.create_table(
        "channels",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "type",
            sa.Enum("shopify", "amazon", "ebay", "woocommerce", "csv", name="channel_type"),
            nullable=False,
        ),
        sa.Column("region_id", sa.UUID(), nullable=True),
        sa.Column("external_shop_id", sa.String(length=200), nullable=True),
        sa.Column("credentials_encrypted", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["region_id"], ["regions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_channels_org_id"), "channels", ["org_id"], unique=False)
    op.create_table(
        "holiday_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("region_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("recurring", sa.Boolean(), nullable=False),
        sa.Column("source", sa.Enum("builtin", "custom", name="holiday_source"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["region_id"], ["regions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_holiday_events_org_id"), "holiday_events", ["org_id"], unique=False)
    op.create_table(
        "products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column(
            "type",
            sa.Enum("finished", "raw_material", "bundle", name="product_type"),
            nullable=False,
        ),
        sa.Column("unit_cost", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["category_id"], ["product_categories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "sku", name="uq_products_org_sku"),
    )
    op.create_index(op.f("ix_products_org_id"), "products", ["org_id"], unique=False)
    op.create_table(
        "purchase_orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("supplier_id", sa.UUID(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=True),
        sa.Column("number", sa.String(length=50), nullable=False),
        sa.Column("status", sa.Enum("draft", "sent", "received", name="po_status"), nullable=False),
        sa.Column("expected_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_purchase_orders_org_id"), "purchase_orders", ["org_id"], unique=False)
    op.create_table(
        "bom_lines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("parent_product_id", sa.UUID(), nullable=False),
        sa.Column("component_product_id", sa.UUID(), nullable=False),
        sa.Column("qty_per_unit", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "parent_product_id <> component_product_id", name="ck_bom_lines_not_self"
        ),
        sa.CheckConstraint("qty_per_unit > 0", name="ck_bom_lines_qty_positive"),
        sa.ForeignKeyConstraint(["component_product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "parent_product_id", "component_product_id", name="uq_bom_lines_parent_component"
        ),
    )
    op.create_index(op.f("ix_bom_lines_org_id"), "bom_lines", ["org_id"], unique=False)
    op.create_table(
        "category_holiday_uplift",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("holiday_event_id", sa.UUID(), nullable=False),
        sa.Column("uplift_pct", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("learned", sa.Boolean(), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=True),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["category_id"], ["product_categories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["holiday_event_id"], ["holiday_events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("category_id", "holiday_event_id", name="uq_cat_holiday_uplift_pair"),
    )
    op.create_index(
        op.f("ix_category_holiday_uplift_org_id"),
        "category_holiday_uplift",
        ["org_id"],
        unique=False,
    )
    op.create_table(
        "channel_listings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("channel_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("external_sku", sa.String(length=200), nullable=True),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel_id", "external_id", name="uq_channel_listings_channel_ext"),
    )
    op.create_index(
        op.f("ix_channel_listings_org_id"), "channel_listings", ["org_id"], unique=False
    )
    op.create_table(
        "inventory_levels",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("on_hand", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("inbound", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column(
            "as_of", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id", "location_id", name="uq_inventory_levels_product_loc"),
    )
    op.create_index(
        op.f("ix_inventory_levels_org_id"), "inventory_levels", ["org_id"], unique=False
    )
    op.create_table(
        "po_lines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("purchase_order_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("received_qty", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["purchase_order_id"], ["purchase_orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "promotions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("channel_id", sa.UUID(), nullable=True),
        sa.Column(
            "type", sa.Enum("paid_ads", "discount", "email", name="promotion_type"), nullable=False
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("discount_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("spend_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "scope", sa.Enum("all", "category", "skus", name="promotion_scope"), nullable=False
        ),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("product_ids", sa.JSON(), nullable=True),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["category_id"], ["product_categories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_promotions_org_id"), "promotions", ["org_id"], unique=False)
    op.create_table(
        "sales_daily",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("channel_id", sa.UUID(), nullable=False),
        sa.Column("region_id", sa.UUID(), nullable=True),
        sa.Column("units", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("revenue", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["region_id"], ["regions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("date", "product_id", "channel_id"),
    )
    op.create_index(op.f("ix_sales_daily_org_id"), "sales_daily", ["org_id"], unique=False)
    op.create_index(
        "ix_sales_daily_org_product_date", "sales_daily", ["org_id", "product_id", "date"]
    )
    # Timescale hypertable when the extension is available (docker-compose / prod use the
    # timescaledb image). Plain Postgres (CI, local tests) keeps a regular table.
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_available_extensions WHERE name = 'timescaledb') THEN
                CREATE EXTENSION IF NOT EXISTS timescaledb;
                PERFORM create_hypertable(
                    'sales_daily', 'date',
                    chunk_time_interval => INTERVAL '90 days',
                    if_not_exists => TRUE
                );
            END IF;
        END $$;
        """
    )
    op.create_table(
        "supplier_products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("supplier_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("lead_time_days", sa.Integer(), nullable=True),
        sa.Column("pack_size", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("supplier_id", "product_id", name="uq_supplier_products_pair"),
    )
    op.create_index(
        op.f("ix_supplier_products_org_id"), "supplier_products", ["org_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_supplier_products_org_id"), table_name="supplier_products")
    op.drop_table("supplier_products")
    op.drop_index("ix_sales_daily_org_product_date", table_name="sales_daily")
    op.drop_index(op.f("ix_sales_daily_org_id"), table_name="sales_daily")
    op.drop_table("sales_daily")
    op.drop_index(op.f("ix_promotions_org_id"), table_name="promotions")
    op.drop_table("promotions")
    op.drop_table("po_lines")
    op.drop_index(op.f("ix_inventory_levels_org_id"), table_name="inventory_levels")
    op.drop_table("inventory_levels")
    op.drop_index(op.f("ix_channel_listings_org_id"), table_name="channel_listings")
    op.drop_table("channel_listings")
    op.drop_index(op.f("ix_category_holiday_uplift_org_id"), table_name="category_holiday_uplift")
    op.drop_table("category_holiday_uplift")
    op.drop_index(op.f("ix_bom_lines_org_id"), table_name="bom_lines")
    op.drop_table("bom_lines")
    op.drop_index(op.f("ix_purchase_orders_org_id"), table_name="purchase_orders")
    op.drop_table("purchase_orders")
    op.drop_index(op.f("ix_products_org_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_holiday_events_org_id"), table_name="holiday_events")
    op.drop_table("holiday_events")
    op.drop_index(op.f("ix_channels_org_id"), table_name="channels")
    op.drop_table("channels")
    op.drop_index(op.f("ix_users_org_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_suppliers_org_id"), table_name="suppliers")
    op.drop_table("suppliers")
    op.drop_index(op.f("ix_regions_org_id"), table_name="regions")
    op.drop_table("regions")
    op.drop_index(op.f("ix_product_categories_org_id"), table_name="product_categories")
    op.drop_table("product_categories")
    op.drop_index(op.f("ix_locations_org_id"), table_name="locations")
    op.drop_table("locations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS channel_type")
    op.execute("DROP TYPE IF EXISTS holiday_source")
    op.execute("DROP TYPE IF EXISTS product_type")
    op.execute("DROP TYPE IF EXISTS po_status")
    op.execute("DROP TYPE IF EXISTS promotion_type")
    op.execute("DROP TYPE IF EXISTS promotion_scope")
