"""org milestones

Revision ID: 878016fb0980
Revises: b503b8941ecf
Create Date: 2026-10-06 11:57:07.149769

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "878016fb0980"
down_revision: str | None = "b503b8941ecf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "org_milestones",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=60), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("props", sa.JSON(), nullable=True),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "key", name="uq_org_milestones_org_key"),
    )
    op.create_index(op.f("ix_org_milestones_org_id"), "org_milestones", ["org_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_org_milestones_org_id"), table_name="org_milestones")
    op.drop_table("org_milestones")
    # ### end Alembic commands ###
