"""forecast runs, forecasts, forecast accuracy

Revision ID: 2ef50a72bfaa
Revises: 128edf56c291
Create Date: 2026-10-03 18:46:19.540544

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "2ef50a72bfaa"
down_revision: str | None = "128edf56c291"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forecast_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("trigger", sa.String(length=20), nullable=False),
        sa.Column("horizon_days", sa.Integer(), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("skus_total", sa.Integer(), nullable=False),
        sa.Column("skus_chronos", sa.Integer(), nullable=False),
        sa.Column("skus_croston", sa.Integer(), nullable=False),
        sa.Column("skus_fallback", sa.Integer(), nullable=False),
        sa.Column("wape", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_forecast_runs_org_id"), "forecast_runs", ["org_id"], unique=False)
    op.create_table(
        "forecast_accuracy",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("model", sa.String(length=30), nullable=False),
        sa.Column("history_days", sa.Integer(), nullable=False),
        sa.Column("zero_share", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("holdout_days", sa.Integer(), nullable=False),
        sa.Column("mape", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("wape", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("wape_chronos", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("wape_stats", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["forecast_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "product_id", name="uq_forecast_accuracy"),
    )
    op.create_index(
        op.f("ix_forecast_accuracy_org_id"), "forecast_accuracy", ["org_id"], unique=False
    )
    op.create_table(
        "forecasts",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("p10", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("p50", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("p90", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("model", sa.String(length=30), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["forecast_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("run_id", "product_id", "date"),
    )
    op.create_index(op.f("ix_forecasts_org_id"), "forecasts", ["org_id"], unique=False)
    op.create_index(
        "ix_forecasts_org_product_date", "forecasts", ["org_id", "product_id", "date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_forecasts_org_product_date", table_name="forecasts")
    op.drop_index(op.f("ix_forecasts_org_id"), table_name="forecasts")
    op.drop_table("forecasts")
    op.drop_index(op.f("ix_forecast_accuracy_org_id"), table_name="forecast_accuracy")
    op.drop_table("forecast_accuracy")
    op.drop_index(op.f("ix_forecast_runs_org_id"), table_name="forecast_runs")
    op.drop_table("forecast_runs")
    # ### end Alembic commands ###
