"""planning: settings, runs, recommendations, product overrides, po fields

Revision ID: 1e6823eed6dd
Revises: b0877fd167af
Create Date: 2026-10-03 21:18:39.255056

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "1e6823eed6dd"
down_revision: str | None = "b0877fd167af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "planning_settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("service_level", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("target_cover_days", sa.Integer(), nullable=False),
        sa.Column("overstock_days", sa.Integer(), nullable=False),
        sa.Column("default_lead_time_days", sa.Integer(), nullable=False),
        sa.Column("production_lead_time_days", sa.Integer(), nullable=False),
        sa.Column("at_risk_buffer_days", sa.Integer(), nullable=False),
        sa.Column("horizon_days", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", name="uq_planning_settings_org"),
    )
    op.create_index(
        op.f("ix_planning_settings_org_id"), "planning_settings", ["org_id"], unique=False
    )
    op.create_table(
        "planning_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("forecast_run_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("trigger", sa.String(length=20), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("products_total", sa.Integer(), nullable=False),
        sa.Column("n_reorder", sa.Integer(), nullable=False),
        sa.Column("n_produce", sa.Integer(), nullable=False),
        sa.Column("health_counts", sa.JSON(), nullable=False),
        sa.Column("cash_by_health", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["forecast_run_id"], ["forecast_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_planning_runs_org_id"), "planning_runs", ["org_id"], unique=False)
    op.create_table(
        "recommendations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(length=10), nullable=False),
        sa.Column("health", sa.String(length=10), nullable=False),
        sa.Column("qty", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("order_by_date", sa.Date(), nullable=True),
        sa.Column("expected_date", sa.Date(), nullable=True),
        sa.Column("supplier_id", sa.UUID(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("on_hand", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("inbound", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("daily_demand", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("lead_time_days", sa.Integer(), nullable=False),
        sa.Column("safety_stock", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("reorder_point", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("stockout_date", sa.Date(), nullable=True),
        sa.Column("days_of_cover", sa.Integer(), nullable=True),
        sa.Column("cash_tied", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("event", sa.String(length=120), nullable=True),
        sa.Column("uplift_pct", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("po_id", sa.UUID(), nullable=True),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["po_id"], ["purchase_orders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["planning_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "product_id", name="uq_recommendations_run_product"),
    )
    op.create_index(op.f("ix_recommendations_org_id"), "recommendations", ["org_id"], unique=False)
    op.create_index(
        "ix_recommendations_org_run", "recommendations", ["org_id", "run_id"], unique=False
    )
    op.add_column(
        "products", sa.Column("service_level", sa.Numeric(precision=4, scale=3), nullable=True)
    )
    op.add_column("products", sa.Column("target_cover_days", sa.Integer(), nullable=True))
    op.add_column("products", sa.Column("lead_time_days", sa.Integer(), nullable=True))
    op.add_column("products", sa.Column("preferred_supplier_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "fk_products_preferred_supplier",
        "products",
        "suppliers",
        ["preferred_supplier_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "purchase_orders", sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "purchase_orders", sa.Column("received_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "purchase_orders",
        sa.Column("currency", sa.String(length=3), nullable=False, server_default="USD"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("purchase_orders", "currency")
    op.drop_column("purchase_orders", "received_at")
    op.drop_column("purchase_orders", "sent_at")
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("fk_products_preferred_supplier", "products", type_="foreignkey")
    op.drop_column("products", "preferred_supplier_id")
    op.drop_column("products", "lead_time_days")
    op.drop_column("products", "target_cover_days")
    op.drop_column("products", "service_level")
    op.drop_index("ix_recommendations_org_run", table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_org_id"), table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index(op.f("ix_planning_runs_org_id"), table_name="planning_runs")
    op.drop_table("planning_runs")
    op.drop_index(op.f("ix_planning_settings_org_id"), table_name="planning_settings")
    op.drop_table("planning_settings")
    # ### end Alembic commands ###
