"""feedback

Revision ID: c423b1150376
Revises: 1bc6b405ddd9
Create Date: 2026-10-06 12:18:04.942637

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "c423b1150376"
down_revision: str | None = "1bc6b405ddd9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=True),
        sa.Column("actor", sa.String(length=200), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("page", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_feedback_org_id"), "feedback", ["org_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_feedback_org_id"), table_name="feedback")
    op.drop_table("feedback")
    # ### end Alembic commands ###
