"""sample data flag

Revision ID: b503b8941ecf
Revises: 78285c53843e
Create Date: 2026-10-06 11:48:35.414977

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "b503b8941ecf"
down_revision: str | None = "78285c53843e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "channels",
        sa.Column("is_sample", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column(
        "locations",
        sa.Column("is_sample", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column(
        "product_categories",
        sa.Column("is_sample", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column(
        "products",
        sa.Column("is_sample", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column(
        "promotions",
        sa.Column("is_sample", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column(
        "suppliers",
        sa.Column("is_sample", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("suppliers", "is_sample")
    op.drop_column("promotions", "is_sample")
    op.drop_column("products", "is_sample")
    op.drop_column("product_categories", "is_sample")
    op.drop_column("locations", "is_sample")
    op.drop_column("channels", "is_sample")
    # ### end Alembic commands ###
