"""covariates: holiday uplift by event name, promo effects, forecast factor

Revision ID: b0877fd167af
Revises: 2ef50a72bfaa
Create Date: 2026-10-03 19:14:44.905210

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "b0877fd167af"
down_revision: str | None = "2ef50a72bfaa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promo_lift_models",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("coef", sa.JSON(), nullable=False),
        sa.Column("n_samples", sa.Integer(), nullable=False),
        sa.Column("post_dip", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("r2", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", name="uq_promo_lift_models_org"),
    )
    op.create_index(
        op.f("ix_promo_lift_models_org_id"), "promo_lift_models", ["org_id"], unique=False
    )
    op.execute(
        "DELETE FROM category_holiday_uplift"
    )  # key changed (event name); rows are re-learned
    op.add_column("category_holiday_uplift", sa.Column("region_id", sa.UUID(), nullable=False))
    op.add_column(
        "category_holiday_uplift", sa.Column("event_name", sa.String(length=100), nullable=False)
    )
    op.alter_column(
        "category_holiday_uplift", "holiday_event_id", existing_type=sa.UUID(), nullable=True
    )
    op.drop_constraint(
        op.f("uq_cat_holiday_uplift_pair"), "category_holiday_uplift", type_="unique"
    )
    op.create_unique_constraint(
        "uq_cat_holiday_uplift_key",
        "category_holiday_uplift",
        ["category_id", "region_id", "event_name"],
    )
    op.drop_constraint(
        op.f("category_holiday_uplift_holiday_event_id_fkey"),
        "category_holiday_uplift",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_cat_holiday_uplift_region",
        "category_holiday_uplift",
        "regions",
        ["region_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_cat_holiday_uplift_event",
        "category_holiday_uplift",
        "holiday_events",
        ["holiday_event_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "forecast_runs", sa.Column("wape_base", sa.Numeric(precision=8, scale=4), nullable=True)
    )
    op.add_column(
        "forecasts",
        sa.Column("factor", sa.Numeric(precision=8, scale=4), nullable=False, server_default="1"),
    )
    op.add_column("forecasts", sa.Column("event", sa.String(length=120), nullable=True))
    op.add_column(
        "holiday_events",
        sa.Column("kind", sa.String(length=20), nullable=False, server_default="retail"),
    )
    op.create_unique_constraint(
        "uq_holiday_events_occurrence", "holiday_events", ["region_id", "name", "start_date"]
    )
    op.add_column(
        "promotions", sa.Column("observed_lift", sa.Numeric(precision=8, scale=4), nullable=True)
    )
    op.add_column(
        "promotions",
        sa.Column("observed_post_dip", sa.Numeric(precision=8, scale=4), nullable=True),
    )
    op.add_column(
        "promotions", sa.Column("baseline_units", sa.Numeric(precision=14, scale=4), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("promotions", "baseline_units")
    op.drop_column("promotions", "observed_post_dip")
    op.drop_column("promotions", "observed_lift")
    op.drop_constraint("uq_holiday_events_occurrence", "holiday_events", type_="unique")
    op.drop_column("holiday_events", "kind")
    op.drop_column("forecasts", "event")
    op.drop_column("forecasts", "factor")
    op.drop_column("forecast_runs", "wape_base")
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("fk_cat_holiday_uplift_event", "category_holiday_uplift", type_="foreignkey")
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(
        "fk_cat_holiday_uplift_region", "category_holiday_uplift", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("category_holiday_uplift_holiday_event_id_fkey"),
        "category_holiday_uplift",
        "holiday_events",
        ["holiday_event_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("uq_cat_holiday_uplift_key", "category_holiday_uplift", type_="unique")
    op.create_unique_constraint(
        op.f("uq_cat_holiday_uplift_pair"),
        "category_holiday_uplift",
        ["category_id", "holiday_event_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "category_holiday_uplift", "holiday_event_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_column("category_holiday_uplift", "event_name")
    op.drop_column("category_holiday_uplift", "region_id")
    op.drop_index(op.f("ix_promo_lift_models_org_id"), table_name="promo_lift_models")
    op.drop_table("promo_lift_models")
    # ### end Alembic commands ###
