"""shopify embedded billing beta

Revision ID: 1bc6b405ddd9
Revises: 878016fb0980
Create Date: 2026-10-06 12:04:58.928609

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "1bc6b405ddd9"
down_revision: str | None = "878016fb0980"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("organizations", sa.Column("shopify_shop", sa.String(length=200), nullable=True))
    op.add_column(
        "organizations", sa.Column("shopify_subscription_id", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "organizations",
        sa.Column("is_beta", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.create_unique_constraint("uq_organizations_shopify_shop", "organizations", ["shopify_shop"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_organizations_shopify_shop", "organizations", type_="unique")
    op.drop_column("organizations", "is_beta")
    op.drop_column("organizations", "shopify_subscription_id")
    op.drop_column("organizations", "shopify_shop")
    # ### end Alembic commands ###
